[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://sns-38a5.onrender.com"
  API_BASE_URL = "https://sns-38a5.onrender.com"
  NEXT_PUBLIC_API_BASE_URL = "https://sns-38a5.onrender.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://sns-38a5.onrender.com"
  API_BASE_URL = "https://sns-38a5.onrender.com"
  NEXT_PUBLIC_API_BASE_URL = "https://sns-38a5.onrender.com"